name: carrental
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


environment:
  sdk: ">=3.5.1 <4.0.0"


#
dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  ionicons: ^0.2.2
  iconsax: ^0.0.8
  flutter_svg: ^2.0.9
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.1.0
  shimmer: ^3.0.0
  flutter_animate: ^4.5.2
  equatable: ^2.0.7
  provider: ^6.1.2

  # Firebase (LATEST for Flutter 3.27 / Dart 3.6)
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.4.3
  google_sign_in: ^6.2.2

  # Networking / Utils
  http: ^1.2.2
  http_parser: ^4.0.2
  logger: ^2.5.0
  intl: ^0.20.2
  connectivity_plus: ^6.1.1
  dio: ^5.5.0
  pretty_dio_logger: ^1.3.1


  # Local Storage
  shared_preferences: ^2.3.4
  sqflite: ^2.4.0
  path_provider: ^2.1.5
  path: ^1.9.0
  get_storage: ^2.1.1

  # Files, Media & Camera
  open_file: ^3.3.1
  image: ^4.2.0
  image_picker: ^1.1.2
  camera: ^0.11.1
  

  # Email / Communication
  mailer: ^6.4.0
  flutter_email_sender: ^7.0.0

  # UI Flow & Animations
  animated_splash_screen: ^1.3.0
  loading_animation_widget: ^1.2.1
  animated_introduction: ^1.0.4
  readmore: ^3.0.0
  flutter_advanced_drawer: ^1.3.7

  # Authentication
  local_auth: ^2.3.0
  flutter_secure_storage: ^9.2.2
  jwt_decode: ^0.3.1


  # Location / Address Picker
  csc_picker: ^0.2.7
  permission_handler: ^11.3.1

  # State Management
  get: ^4.6.6

  # Real-Time Chat
  web_socket_channel: ^3.0.1
  flutter_chat_ui: ^1.6.12

  # Maps, GPS, Trackers, Branch Nearby Search
  google_maps_flutter: ^2.6.1
  geolocator: ^13.0.2 
  geocoding: ^2.2.0
  flutter_polyline_points: ^2.0.0
  geolocator_android: 4.6.0

  # File Uploads (User IDs, Driver docs, Images)
  file_picker: ^8.0.3
  flutter_image_compress: ^2.3.0

  # Notifications
  firebase_messaging: ^15.0.2
  flutter_local_notifications: ^17.1.0

  # Date & Time Pickers for Booking
  table_calendar: ^3.1.2
  syncfusion_flutter_datepicker: ^29.1.38

  # Payments (Driver bookings / reservations)
  flutter_stripe: ^11.1.0

  # State Management (Better for large app
  flutter_riverpod: ^2.5.1

  # Routing (You need this for huge project)
  go_router: ^14.2.0

  #Background Services (For live tracking)
  flutter_background_service: ^5.0.5

  #
  #




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
 assets:
   - assets/images/

 
 uses-material-design: true

 